### PR TITLE
Use domain names for banks instead of IPs

### PR DESCRIPTION
**Pull request by avinashupadhya99**

### CODE REVIEW

**Comment by mrbusysky** [comment]
#629

**Comment by buckyroberts** [comment]
This will require backend updates and quite a few additional tests as well https://github.com/thenewboston-developers/thenewboston-python/blob/development/src/thenewboston/models/network_node.py#L12 We are adding in domain name support for beta but the alpha nodes only support static IP addresses now.

**Review by angle943 — APPROVED** [review]

**Review by angle943 — CHANGES_REQUESTED** [review]
Screen Shot 2021-09-07 at 7 57 51 PM

This field should still work for ip addresses. Could you update the regex to account for both situations?

**Comment by avinashupadhya99** [comment]
> This field should still work for ip addresses. Could you update the regex to account for both situations?

Sure, I will do that change

**Comment by mrbusysky** [comment]
You can close that @avinashupadhya99

**Pull request closed without merging**
