### PR TITLE
Updated bank api calls to use the js sdk 

### PR DESCRIPTION
**Pull request by tomijaga**
#585 

Merge after : #609

### CODE REVIEW

**Comment by zinoadidi** [comment]
@tomijaga you read my mind. 

Just keep going when Justin gets back he will look at all of them

**Comment by tomijaga** [comment]
@zinoadidi If he finds does not approve of a change on one of the early PR's it going to cause conflicts with the pr's I submitted after that one. Which will just be more work.

**Comment by tomijaga** [comment]
@zinoadidi I feel like I will end up creating more work for myself if Justin comes back and doesn't approve of a change I made in the earlier Pr's.

**Comment by zinoadidi** [comment]
ok, maybe we can get one of the other contributors who know about this account manager to take a look first, then when Justin shows up, he just rechecks it, that way there is less room for errors.

We could also get bucky to help us merge them since we will still have to review when we merge to the main branch anyways.
That way if something is wrong you only need to create a new PR as opposed to changing existing ones

**Comment by stweyel** [comment]
> ok, maybe we can get one of the other contributors who know about this account manager to take a look

@tomijaga @zinoadidi ...if you check mine... i'll check yours ;-)
No seriously. I'll install your branch and test it. Maybe it can help to reduce approval/testing times.
If anyone may have a look at my PR #608 feel free to comment

**Comment by tomijaga** [comment]
@stweyel we still won't be able to merge it. 
The issue was made from a windows device. 
I use a mac so i won't be able to help with this

**Review by zinoadidi — APPROVED** [review]

**Pull request merged**
