### PR TITLE
Add Friend #56

### PR DESCRIPTION
**Pull request by Hristijan95**
Don't merge it yet (I need some info that I asked on slack to finish it).

### CODE REVIEW

**Comment by Hristijan95** [comment]
Done.

**Comment by angle943** [comment]
could you merge in the master branch into this @Hristijan95 ?

**Comment by Hristijan95** [comment]
It's done, should be okay to merge now.

**Comment by angle943** [comment]
https://github.com/thenewboston-developers/Account-Manager/pull/75

**Pull request closed without merging**
