### PR TITLE
Accounts -> Send Points Modal (UI) #35

### PR DESCRIPTION
**Pull request by Hristijan95**
I've made the points send form, except for the TOTAL Tx calculation because I've never worked with formik. I had to go, I will finish it tomorrow if no one commits an update until then.

### CODE REVIEW

**Comment by angle943** [comment]
Screen Shot 2020-07-14 at 6 12 15 PM

Let's try to make the UI more closely resemble the mocks. For example, the width of the modal. One thing great about Figma (the software that has the mocks), is that you can hover over elements and it tells you the CSS:

Screen Shot 2020-07-14 at 6 16 07 PM

Overall very solid work! And don't worry about the Total Tx calculation, i'll add that in once you can tidy up some of the styling

**Comment by Hristijan95** [comment]
Sure, I will adapt the UI to the figma designs as close as possible.

I don't really understand what do you mean by this: "check out the post i added in the conversations"?

Also, there is a slack link on thenewboston.com website, but it's expired, would be easier if someone renew the link for better communication.

**Comment by Hristijan95** [comment]
I've completed the styling, but for some reason my new commits from [my fork](https://github.com/Hristijan95/Account-Manager) are not appearing in this pull request. Do you possibly know why is that?

I am new in GitHub contributions, but according to my knowledge, when I pushed to the branch in my fork, the commits should have appeared here as well, but I can see that's not the case.

**Comment by angle943** [comment]
fantastic job. I made a couple changes and will merge it in. https://github.com/thenewboston-developers/Account-Manager/pull/42

**Pull request closed without merging**
