### PR TITLE
#Issue-392 properly fixed

### PR DESCRIPTION
**Pull request by accessdeniedIT**
Forgot for a sec it was an appimage

### CODE REVIEW

**Comment by lapstjup** [comment]
@accessdeniedIT Can you give a quick brief about this change ?

**Comment by accessdeniedIT** [comment]
Fixes Linux Icon issues

**Comment by accessdeniedIT** [comment]
I closed it.

**Comment by accessdeniedIT** [comment]
@lapstjup

**Comment by lapstjup** [comment]
@accessdeniedIT I think #392 is the issue this fix is for ? It shouldn't be closed until the PR for it gets merged.

**Comment by lapstjup** [comment]
@thesanjeevsharma Do we want relative imports for assets ? Also @accessdeniedIT - where is the png file saved? I cannot see any new png file added to assets as part of this PR.

**Comment by accessdeniedIT** [comment]
it's an appimage, the image/png already exist in a temp file that itself creates @lapstjup

**Comment by thesanjeevsharma** [comment]
> @thesanjeevsharma Do we want relative imports for assets ? 

Relative imports for same directory, else absolute imports everywhere. @lapstjup 

Here, it should be absolute as it's outside main dir.

**Pull request closed without merging**
