### PR TITLE
Fix mac icon assignments

### PR DESCRIPTION
**Pull request by stweyel**
issue #543
Icon paths in forge.config.js have been ignored.
Moved mac icon path config from forge.config.js to electron-builder.json

Account Number
94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

### CODE REVIEW

**Review by amarjeet987 — APPROVED** [review]
@angle943 This can be closed I guess.

**Comment by angle943** [comment]
@amarjeet987 no this ones fine because it was before my PR

**Comment by angle943** [comment]
oh my lord that looks so good :D

Screen Shot 2021-03-17 at 10 14 02 PM

**Comment by amarjeet987** [comment]
> oh my lord that looks so good :D
> 
> Screen Shot 2021-03-17 at 10 14 02 PM

Yeah, aesthetic xD

**Pull request merged**
