### PR TITLE
Account Number Link Issue #363 Fix

### PR DESCRIPTION
**Pull request by Hristijan95**
Fixed issue #363

### CODE REVIEW

**Comment by Hristijan95** [comment]
This fixes the issue, however, I am not sure if the solution is the best way to do it, I will try to explain what I mean in the shortest possible way.

So, we have Account/index.js and Friend/index.js components. We currently use the Account/index.js when clicking on any account number in the transactions table on a friend. When we click on any acc number, we don't know if that account is one of our friends, or some random account number that we have no idea about - so I guess that's the reason why we go directly to the Account/index.js. So, now everything works with the solution, but we have a scenario where you are on the Account/index.js, but you are actually looking at a friend - so we are using the component in a wrong way.
My question is, do you want me to change the code BEFORE opening the component and do the actual check before navigation, so I will navigate to the right component, or it's okay with the current solution?

It will be something like:
`if (isFriend(accountNumber)) {open Friend/index.js} else {open Account/index.js}`

The only visible difference with this solution will be that when you open the Friend/index.js component you have and options menu on the top right to edit / remove the friend. Or maybe the desired scenario is for that menu to be hidden? Because there is a logic in Account/index.js to hide that menu if you are not at your own profile - so I guess that logic is maybe for this exact case? Anyway, just let me know what is the desired case and if needed, I will change it and commit the changes on this PR. 
I hope I was able to explain what I mean.

**Review by charnysh-dev — COMMENTED** [review]
Great thinking! I know what you mean. I think we need to update not only the account name but also the related menus and features. So you could go ahead on navigating to the correct component (Account/index.js vs Friend/index.js)

**Comment by angle943** [comment]
@buckyroberts @Hristijan95 i like the method that you have mentioned in your comment. Furthermore, I think we should get rid of the route `/friend` completely. Keep just `/account`, and then conditionally render the `Account` component or the `Friend` component depending on whether the account is a friend or not

**Comment by angle943** [comment]
per our discussion on this PR, i added a comment of an acceptance criteria on the issue. Closing this PR for now

**Pull request closed without merging**
