### PR TITLE
Toggle and Paganiated Result Position Fixed

### PR DESCRIPTION
**Pull request by manishram**
Fix: https://github.com/thenewboston-developers/Account-Manager/issues/590

**Account Number:** `0f92e975101eb96cea80dce430d74efd3172fa229377818d467ded85dcf2ab6c`

### CODE REVIEW

**Comment by angle943** [comment]
closing for now, there are two issues:

1) I'm a little wary of using things such as `top: 148px` since it might change in a future scenario. Also, we have this responsive behavior, and it breaks the page with it (`Account` and `Transactions` tab are hidden underneath the fixed section):
Screen Shot 2021-03-11 at 8 23 04 PM

2) This is something I noticed before when I was trying to make this section sticky a couple weeks ago: 
Screen Shot 2021-03-11 at 8 24 11 PM

Whenever you scroll, a small portion from the list seems to be seeping out. I remember trying to fix this for like an hour, and gave up in frustration. Do you know how we might be able to fix this?

**Comment by manishram** [comment]
I'll give it try after an hour.

**Comment by manishram** [comment]
@angle943 initially I was not using `top: 148px` this solves all the problem you mentioned above and possibly this: **small portion from the list seems to be seeping out** also (I don't see this problem in windows). But it is giving new problem. And the problem is that the header of the table gets hidden below the sticky `<div>`.  Giving `margin-top` to the table actually also gives 'margin-top' to the sticky `<div>` and pulls it down. The only solution to this problem that seems to work for me is to make a pseudo `<div>` above `table `with the height of `50px` so we don't need to give `margin-top` to the table.

**Comment by manishram** [comment]
Alright I figured it out. changed `--page-table-padding: 0 0 24px` to `--page-table-padding: 50px 0 24px` i.e. giving padding-top of 50px

**Pull request closed without merging**
