### PR TITLE
Introduce fix for #431

### LINKED ISSUE #431: TNB Account Manager (Mac) - Apple cannot check it for malicious software
**Bug Description**
“TNB Account Manager” can’t be opened because Apple cannot check it for malicious software.

**Steps to Reproduce**
1. Install the dmg from thenewboston website
2. Open the app
4. See permission error

**Expected behavior**
Open the app 

**Actual behavior**
Apple doesn't want to open the app because it cannot check it for malicious software 

**Screenshots/Recordings**
Screen Shot 2020-11-06 at 4 02 16 PM

**OS and Browser**
 - OS: macOS Catalina 10.15.3
 - Browser: Chrome

**Additional context**
Laptop Specs

MacBook Pro (13-inch, Mid 2012)
2.5 GHz Dual-Core Intel Core i5
8 GB 1600 MHz DDR3
Intel HD Graphics 4000 1536 MB

**Account Number**
e483f8366c1c760ba384225bc19e44c63e012f8149a181a9a0f3e34ac5c336e3

### PR DESCRIPTION
**Pull request by ionutzaharia**
Try to fix error for unknown mac publisher. Fixes #431 as per https://www.electron.build/configuration/mac

### CODE REVIEW

**Comment by nishp77** [comment]
@ionutzaharia just wanna ask if it did work or not?

**Comment by ionutzaharia** [comment]
@nishp77 the build works locally, but it has to be tested using the developer apple credentials.

**Review by charnysh-dev — COMMENTED** [review]
I don't think it's the solution
https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution
 (https://github.com/thenewboston-developers/Account-Manager/issues/431#issuecomment-726107690)

**Comment by angle943** [comment]
https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

**Comment by itsnikhil** [comment]
@ionutzaharia what is your account number?

**Comment by ionutzaharia** [comment]
Hello @itsnikhil, 37f45e2eec79ff2cff9460d980b048e97e54a256831427ee8f8a6f257cbd007e
Thank you!

**Pull request merged**
